# Generated by Django 4.2.5 on 2023-10-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
