# Generated by Django 4.2.5 on 2023-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0002_remove_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('driver_number', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('service_branch', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=10)),
                ('service_date', models.DateField()),
            ],
        ),
    ]
