# Generated by Django 4.2.5 on 2023-11-04 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0006_customuser_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='customername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
