# Generated by Django 4.2.5 on 2023-11-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0007_alter_servicebooking_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='customername',
            new_name='customer',
        ),
    ]
