# Generated by Django 4.2.5 on 2023-11-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0008_rename_customername_servicebooking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='customer',
            new_name='customername',
        ),
    ]
