# Generated by Django 4.2.5 on 2023-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0009_rename_customer_servicebooking_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='customername',
            field=models.CharField(max_length=100),
        ),
    ]
