# Generated by Django 4.2.5 on 2023-11-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0015_remove_userprofile_customername_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
