# Generated by Django 4.2.5 on 2023-11-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='customername',
        ),
    ]
