# Generated by Django 4.2.5 on 2023-11-07 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0017_remove_customuser_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='customername',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
