# Generated by Django 4.2.5 on 2023-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0018_remove_servicebooking_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
