# Generated by Django 4.2.5 on 2023-11-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0020_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
