# Generated by Django 4.2.5 on 2023-12-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0022_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='categories',
            field=models.CharField(blank=True, default='Uncategorized', max_length=100, null=True),
        ),
    ]
