# Generated by Django 4.2.5 on 2024-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0025_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
