# Generated by Django 4.2.5 on 2024-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0026_parts_additional_details_parts_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('slot_number', models.IntegerField()),
                ('status', models.CharField(default='Available', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booked_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking_status',
            field=models.CharField(default='Available', max_length=10),
        ),
    ]
