# Generated by Django 4.2.5 on 2024-01-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0027_serviceslot_servicebooking_booked_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceslot',
            name='service_date',
        ),
    ]
