# Generated by Django 4.2.5 on 2024-01-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0029_delete_serviceslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='booking_status',
        ),
    ]
