# Generated by Django 4.2.5 on 2024-02-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0030_remove_servicebooking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='booked_slot',
        ),
    ]
