# Generated by Django 4.2.5 on 2024-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0031_remove_servicebooking_booked_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
