# Generated by Django 4.2.5 on 2024-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0032_servicebooking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
