# Generated by Django 5.0.2 on 2024-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0033_servicebooking_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vehicle_model', models.CharField(choices=[('lightvehicle', 'Light Vehicle'), ('trucks', 'Trucks'), ('buses', 'Buses')], max_length=20)),
                ('vehicle_usage', models.CharField(choices=[('goodscarriers', 'Goods Carriers'), ('passenger', 'Passenger')], max_length=20)),
                ('vehicle_application', models.CharField(choices=[('beverage', 'Beverage'), ('buildingmaterial', 'Building Material'), ('constructionhardware', 'Construction and Hardware')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=10)),
                ('transmission_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semiautomatic', 'Semi-Automatic')], max_length=15)),
                ('engine_size', models.IntegerField(blank=True, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('fuel_tank_capacity', models.FloatField(blank=True, null=True)),
                ('vehicle_colors', models.JSONField(blank=True, default=list, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_slot',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
