# Generated by Django 5.0.2 on 2024-02-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0034_vehicle_alter_servicebooking_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='images',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_colors',
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='partsapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partsapp.vehicle')),
            ],
        ),
    ]
