# Generated by Django 5.0.2 on 2024-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0035_remove_vehicle_images_remove_vehicle_vehicle_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='VehicleColor',
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
