# Generated by Django 5.0.2 on 2024-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0039_vehicle_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
