# Generated by Django 5.0.2 on 2024-02-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0042_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
