# Generated by Django 5.0.2 on 2024-02-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0044_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('insurance_number', models.CharField(max_length=20)),
                ('insurance_expire_date', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('service_branch', models.CharField(max_length=50)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
