# Generated by Django 5.0.2 on 2024-03-02 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0046_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
