# Generated by Django 5.0.2 on 2024-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0047_booking_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('insuranceType', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicleModelType', models.CharField(max_length=100)),
            ],
        ),
    ]
