# Generated by Django 5.0.2 on 2024-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0048_insurancequote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceQuote',
        ),
    ]
