# Generated by Django 5.0.2 on 2024-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0050_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_usage', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission_type', models.CharField(max_length=20)),
                ('insurance_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renew_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
