# Generated by Django 5.0.2 on 2024-03-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0051_deletedinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_usage', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission_type', models.CharField(max_length=20)),
                ('insurance_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renew_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsapp.insurance')),
            ],
        ),
    ]
