# Generated by Django 5.0.2 on 2024-03-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0053_wishlist_delete_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
