# Generated by Django 5.0.2 on 2024-03-29 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0055_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsapp.vehicle')),
            ],
            options={
                'unique_together': {('user', 'vehicle')},
            },
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
