# Generated by Django 5.0.2 on 2024-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0056_wishlistitem_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
