# Generated by Django 5.0.2 on 2024-04-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0059_booking_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='confirmedvehicle',
            name='registration_number',
        ),
    ]
