# Generated by Django 5.0.2 on 2024-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0060_remove_booking_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
            ],
        ),
    ]
