# Generated by Django 5.0.2 on 2024-04-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0062_confirmedvehicle_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedvehicle',
            name='registration_number',
        ),
    ]
