# Generated by Django 5.0.2 on 2024-04-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0063_remove_confirmedvehicle_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedvehicle',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partsapp.vehicleregistration'),
        ),
    ]
