# Generated by Django 5.0.2 on 2024-04-06 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0064_confirmedvehicle_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
