# Generated by Django 5.0.2 on 2024-04-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0067_remove_paymentrecord_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='insurancenew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partsapp.insurancenew'),
        ),
    ]
