# Generated by Django 5.0.2 on 2024-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0068_paymentrecord_insurancenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
