# Generated by Django 5.0.2 on 2024-04-08 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0069_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=20)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('payment_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partsapp.paymentrecord')),
            ],
        ),
    ]
