# Generated by Django 5.0.2 on 2024-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0070_confirmedpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmedPayment',
        ),
    ]
