# Generated by Django 5.0.2 on 2024-04-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0072_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('policy_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
