# Generated by Django 5.0.2 on 2024-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsapp', '0073_confirmedinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
